//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.Learning.ADO.ControlTask.RentACar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RetroCarContext : DbContext
    {
        public RetroCarContext()
            : base("name=RetroCarContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_ArchiveСontract> t_ArchiveСontract { get; set; }
        public virtual DbSet<t_Car> t_Car { get; set; }
        public virtual DbSet<t_Client> t_Client { get; set; }
        public virtual DbSet<t_InfoAuto> t_InfoAuto { get; set; }
        public virtual DbSet<t_Manager> t_Manager { get; set; }
        public virtual DbSet<t_Сontract> t_Сontract { get; set; }
    
        public virtual ObjectResult<usp_FreeCarOfDate_Result> usp_FreeCarOfDate(Nullable<System.DateTime> dateStart, Nullable<System.DateTime> dateEnd)
        {
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_FreeCarOfDate_Result>("usp_FreeCarOfDate", dateStartParameter, dateEndParameter);
        }
    }
}
