//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.Learning.ADO.ControlTask.RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ArchiveСontract
    {
        public int IDContract { get; set; }
        public string NomerAuto { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<int> IDManager { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<decimal> Summa { get; set; }
    }
}
