//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.Learning.ADO.ControlTask.RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Car()
        {
            this.t_Сontract = new HashSet<t_Сontract>();
        }
    
        public string NomerAuto { get; set; }
        public Nullable<int> IDInfoAuto { get; set; }
        public Nullable<int> Probeg { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual t_InfoAuto t_InfoAuto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Сontract> t_Сontract { get; set; }
    }
}
