//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.Learning.ADO.ControlTask.RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_InfoAuto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_InfoAuto()
        {
            this.t_Car = new HashSet<t_Car>();
        }
    
        public int IDInfoAuto { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<short> KolvoMest { get; set; }
        public Nullable<short> YearOfR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Car> t_Car { get; set; }
    }
}
