//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.Learning.ADO.ControlTask.RentACar.RetroCarModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ArchiveСontract
    {
        public int IDContract { get; set; }
        public string CarNumber { get; set; }
        public int IDClient { get; set; }
        public int IDManager { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public decimal Summa { get; set; }
        public System.DateTime DateOfConclusion { get; set; }
        public string Status { get; set; }
        public string Cause { get; set; }
    }
}
