//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.Learning.ADO.ControlTask.RentACar.RetroCarModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_InfoCar
    {
        public string Brand { get; set; }
        public string Model { get; set; }
        public string CarNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Status { get; set; }
        public string Cause { get; set; }
    }
}
